### ISSUE TITLE
doesnt work as expected with hyperterm-one-light

### ISSUE THREAD

**Issue by iamstarkov** [magus/hyper-transparent-dynamic#1]
https://github.com/andrepolischuk/hyper-one-light

two issues here:

1. border is contrasting with vibrant body
2. vibrancy doesnt work for tabs

![screen shot 2017-03-13 at 10 55 52](https://cloud.githubusercontent.com/assets/559321/23849390/bb7e1008-07db-11e7-8331-59f022badebf.png)

do you think we can fix it together?

**Comment by magus** [comment]
Looking at the source for that theme
https://github.com/andrepolischuk/hyper-one-light/blob/master/index.js

Seems like `enableVibrancy` is a custom config which when disabled sets the tab color forcefully as a solid color and then sets some CSS. Then `hyper-transparent-dynamic` will modify backgroundColor but the end result is that the tabs have already been styled with a solid color. I'm not sure the best way to resolve this actually, if the theme hard codes the styles we might consider adding css to try to overwrite them I guess?

**Comment by iamstarkov** [comment]
@andrepolischuk what do u think?

**Comment by ghost** [comment]
I rewrite colors with rgba. Its ok?

<img width="991" alt="screen shot 2017-03-14 at 15 52 18" src="https://cloud.githubusercontent.com/assets/8956796/23901428/4155b148-08ce-11e7-8c2d-1680efc9c1f8.png">

**Comment by iamstarkov** [comment]
yeah

**Comment by ghost** [comment]
Published `hyper-one-light` as v1.1.1

**Comment by iamstarkov** [comment]
@andrepolischuk you are the best
