### ISSUE TITLE
Doesn't work in Hyper 3

### ISSUE THREAD

**Issue by v1rtl** [magus/hyper-transparent-dynamic#10]
**Hyper version** 3.0.2

**Plugin version** 1.2

**OS** Ubuntu 18.04

Instead of being transparent it just becomes dark:

![image](https://user-images.githubusercontent.com/35937217/63691749-b43a4a00-c818-11e9-9348-e53df1769943.png)

**Comment by tianxiewuhua** [comment]
> **Hyper version** 3.0.2
> 
> **Plugin version** 1.2
> 
> **OS** Ubuntu 18.04
> 
> Instead of being transparent it just becomes dark:
> 
> ![image](https://user-images.githubusercontent.com/35937217/63691749-b43a4a00-c818-11e9-9348-e53df1769943.png)

this feature is only supported in MacOS

**Comment by v1rtl** [comment]
> > **Hyper version** 3.0.2
> > **Plugin version** 1.2
> > **OS** Ubuntu 18.04
> > Instead of being transparent it just becomes dark:
> > ![image](https://user-images.githubusercontent.com/35937217/63691749-b43a4a00-c818-11e9-9348-e53df1769943.png)
> 
> this feature is only supported in MacOS

okay, closing then
